### ISSUE TITLE
Possible contradiction between code and documentation/paper

### ISSUE THREAD

**Issue by bednik** [LDeakin/VkVolume#2]
Hi! 
I am working on implementing volume rendering directly on a HoloLens 2 for my master thesis, and decided to try implementing ESS with Chebyshev distance maps (Using Unity as my engine for easier AR integration, so I have to translate to HLSL and C#). 
I just noticed that both in the paper and the documentation for distance_map.comp the first transformation expects occupied regions to have a value of 255. However, occupied regions are defined as 0 in occupancy_map.comp. I was wondering which one is correct?

I am also currently experiencing an unknown bug (likely something in my fragment shader), and I'm not sure what it comes from. Had to make sure it wasn't this. 😅 Looking at my currently resulting distance map, it seems like occupied=0 makes most sense, unless I am misunderstanding something.

**Comment by LDeakin** [comment]
Thank you for pointing this out! Indeed, the paper and comments at the top of the `distance_map.comp` have it backwards.
So yes, occupied regions = 0, empty = 255.

**Comment by LDeakin** [comment]
Fixed in f72e8c6f3f8689c8ba2b8015e5ae8519c2722cdb
