### ISSUE TITLE
distance_map.comp: One of the planes of the map is all black

### ISSUE THREAD

**Issue by bednik** [LDeakin/VkVolume#3]
Hello there, me again! I noticed when I ported this compute shader to Unity that one of the planes in the 3D texture is all black. I fixed it by storing the initial value (gi1jk) in the output's initial position. I'm not sure if that's the correct way of doing it, but I thought I could mention it here :)

In Unity, I added this line: OutMap[position] = ByteToFloat[uint2(prev, 0)];, which is basically storing gi1jk in the output before starting the for loops.

Adding a couple of images to explain better:

![image](https://user-images.githubusercontent.com/32166304/173077613-7c699147-d4ed-4d85-a4e1-2e68c9b6f1c0.png)
![image](https://user-images.githubusercontent.com/32166304/173078052-b9982d12-90dd-4209-8512-5e263f580ac0.png)

**Comment by LDeakin** [comment]
Hmm, I'm not seeing this occurring on any of the test images.
Could you see if it happens when you run your image through this codebase, in case there is a typo in your port?

**Comment by bednik** [comment]
Looking at the code it doesn't look like a typo, but I'll try running it through your application sometime next week! I'm afraid my problem might be a bit weirder 😅

HLSL, at least with Unity, doesn't support loading byte (or uint) data from textures, so it will always be a float between 0 and 1. The way I "fixed" that was by making a byte texture consisting of the values 0-255 that I could use as a lookup-table with [distance, 0] as coordinates when storing the distance, and when loading from the input image I would multiply the value by  255 and then floor it. It's possible that there are some rounding errors that come from this.
